webtalk_init -webtalk_dir /home/zab180/3700/1_verilog/1_modules/2_build/xsim.dir/sim/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 21 19:03:32 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "df80a372-cc9d-4d82-8713-359b0cd62b38" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b8c0b727-e9bb-4103-aad2-98afe548b551" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "60" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7502 32-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2539.908 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "63.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "170 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116464_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3756797389 -regid "" -xml /home/zab180/3700/1_verilog/1_modules/2_build/xsim.dir/sim/webtalk/usage_statistics_ext_xsim.xml -html /home/zab180/3700/1_verilog/1_modules/2_build/xsim.dir/sim/webtalk/usage_statistics_ext_xsim.html -wdm /home/zab180/3700/1_verilog/1_modules/2_build/xsim.dir/sim/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
